#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"
DEBUG="yes"
redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio "${APP_DIR}/unpackerr" ${ARGS}
