#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------

----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/unpackerr.conf" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/unpackerr.conf] file."
    cp "${APP_DIR}/unpackerr.conf.example" "${CONFIG_DIR}/unpackerr.conf"
    find "${CONFIG_DIR}/unpackerr.conf" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
