#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/app/unpackerr.conf" ]]; then
    cp "${APP_DIR}/unpackerr.conf" "${CONFIG_DIR}/app/unpackerr.conf"
    chown hotio:hotio "${CONFIG_DIR}/app/unpackerr.conf"
fi
