#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ -f "${CONFIG_DIR}/app/unpackerr.conf" ]]; then
    echo "Copying custom \"unpackerr.conf\"..."
    cp -f "${CONFIG_DIR}/app/unpackerr.conf" /etc/unpackerr/unpackerr.conf
else
    echo "No custom \"unpackerr.conf\" found. Using defaults."
fi
